- name: Install openjdk
  apt: name=openjdk-7-jre-headless state=latest
  
- name: copy mojo udev rules
  copy: src=mojo-loader-1.2.2/driver/99-mojo.rules dest=/etc/udev/rules.d/99-mojo.rules

- name: add vagrant to dialout group
  user: name=vagrant groups=dialout append=yes

- name: copy mojo loader desktop launcher
  copy: src=roles/mojo/files/mojo_loader.desktop dest=/home/vagrant/Desktop/